sonar.projectKey=cimavia
sonar.organization=cimavia

sonar.sources=apps/api/src,packages/shared/src,packages/tokens/src
sonar.exclusions=\
  apps/mobile/**,\
  apps/web/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/*.spec.ts,\
  **/*.test.ts,\
  apps/api/src/generated/**

sonar.tests=apps/api/src,packages/shared/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.typescript.tsconfigPath=apps/api/tsconfig.json

sonar.sourceEncoding=UTF-8
