/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MyCoachRouteImport } from './routes/my-coach'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as SessionsSessionIdFeedbackRouteImport } from './routes/sessions.$sessionId.feedback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoachRoute = MyCoachRouteImport.update({
  id: '/my-coach',
  path: '/my-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const SessionsSessionIdFeedbackRoute =
  SessionsSessionIdFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-coach': typeof MyCoachRoute
  '/planning': typeof PlanningRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/plans/': typeof PlansIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-coach': typeof MyCoachRoute
  '/planning': typeof PlanningRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/plans': typeof PlansIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-coach': typeof MyCoachRoute
  '/planning': typeof PlanningRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/plans/': typeof PlansIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athletes'
    | '/feedbacks'
    | '/forgot-password'
    | '/invoices'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-coach'
    | '/planning'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/plans/$planId'
    | '/sessions/$sessionId'
    | '/plans/'
    | '/sessions/'
    | '/sessions/$sessionId/feedback'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athletes'
    | '/feedbacks'
    | '/forgot-password'
    | '/invoices'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-coach'
    | '/planning'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/plans/$planId'
    | '/plans'
    | '/sessions'
    | '/sessions/$sessionId/feedback'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/athletes'
    | '/feedbacks'
    | '/forgot-password'
    | '/invoices'
    | '/library'
    | '/login'
    | '/messages'
    | '/my-coach'
    | '/planning'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/plans/$planId'
    | '/sessions/$sessionId'
    | '/plans/'
    | '/sessions/'
    | '/sessions/$sessionId/feedback'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthletesRoute: typeof AthletesRoute
  FeedbacksRoute: typeof FeedbacksRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoicesRoute: typeof InvoicesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyCoachRoute: typeof MyCoachRoute
  PlanningRoute: typeof PlanningRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  PlansIndexRoute: typeof PlansIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-coach': {
      id: '/my-coach'
      path: '/my-coach'
      fullPath: '/my-coach'
      preLoaderRoute: typeof MyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/feedback': {
      id: '/sessions/$sessionId/feedback'
      path: '/feedback'
      fullPath: '/sessions/$sessionId/feedback'
      preLoaderRoute: typeof SessionsSessionIdFeedbackRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
  }
}

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdFeedbackRoute: typeof SessionsSessionIdFeedbackRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdFeedbackRoute: SessionsSessionIdFeedbackRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthletesRoute: AthletesRoute,
  FeedbacksRoute: FeedbacksRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoicesRoute: InvoicesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyCoachRoute: MyCoachRoute,
  PlanningRoute: PlanningRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  PlansIndexRoute: PlansIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
